auth-server:
  host: "http://localhost:${wiremock.server.port:8001}"
  client-id: testes
  client-secret: 123456

web-client:
  auth-server-url: "${auth-server.host}"
  users:
    read-timeout: 1000
    connect-timeout: 1000
  address-url: "http://localhost:${wiremock.server.port:8002}/ws"

resilience4j.bulkhead:
  configs:
    default:
      maxConcurrentCalls: 1
  instances:
    users:
      baseConfig: default

resilience4j.circuitbreaker:
  configs:
    default:
      minimumNumberOfCalls: 3
      permittedNumberOfFailuresInHalfOpenState: 1
      failureRateThreshold: 50
      slowCallRateThreshold: 50
      slowCallDurationThreshold: 300

resilience4j.retry:
  configs:
    default:
      maxAttempts: 2
      waitDuration: 100

spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
    url: jdbc:h2:mem:customer-ms;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
  test:
    database:
      replace: none
  h2:
    console:
      enabled: true
      path: /h2
  flyway:
    enabled: true
    locations: classpath:db/migration