logging:
  level:
    ROOT: WARN
    com.kaua.ecommerce: DEBUG

auth-server:
  token-uri: /oauth2/token

web-client:
  auth-server:
    base-url: "${web-client.auth-server-url}/api"
    read-timeout: 2_000 # milliseconds
    connect-timeout: 2_000 # milliseconds
  users:
    base-url: "${web-client.auth-server-url}/api/v1/users"
    read-timeout: 2_000 # milliseconds
    connect-timeout: 2_000 # milliseconds

jobs:
  client-credentials:
    refresh-rate-minutes: 3
    refresh-initial-delay-minutes: 4

server:
  port: 8081
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  undertow:
    threads:
      worker: 64
      io: 4

spring:
  flyway:
    enabled: false
  datasource:
    url: jdbc:postgresql://${postgres.url}/${postgres.schema}
    username: ${postgres.username}
    password: ${postgres.password}
    hikari:
      auto-commit: false
      connection-timeout: 250
      max-lifetime: 600000
      maximum-pool-size: 20
      minimum-idle: 10
      pool-name: master
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      "[hibernate.dialect]": org.hibernate.dialect.PostgreSQLDialect
      "[hibernate.generate_statistics]": false
      "[hibernate.connection.provider_disables_autocommit]": true
      hibernate:
        jdbc:
          batch_size: 10
        order_inserts: true
        order_updates: true